In [44]:
import pandas as pd
import matplotlib.pyplot as plt

# I. Property Type

## I. Apartments

In [72]:
df_apart = pd.read_csv("apartment-for-sale.csv")
for idx, price in enumerate(df_apart['price']):
    if price < 90000000:
        df_apart.at[idx, 'price'] = 90000000
    elif price > 480000000:
        df_apart.at[idx, 'price'] = 480000000
        
# Data preprocessing
df_apart['district'] = df_apart['district'].str.lower().str.strip()
# Drop rows with missing values in the 'date' column
df_apart = df_apart.dropna(subset=['date'])
# Convert the 'date' column to a proper datetime format
df_apart['date'] = pd.to_datetime(df_apart['date'])
# Extracting the quarter from the 'date' column and creating a new 'quarter' column
df_apart['quarter'] = df_apart['date'].dt.quarter
desired_districts = ['gasabo', 'kicukiro', 'nyarugenge']
df_apart_2022 = df_apart[(df_apart['district'].isin(desired_districts)) & (df_apart['date'].dt.year == 2022)].copy()
# Computing the median price of houses for sale in 2022 by quarter
median_apart_prices_by_quarter = df_apart_2022.groupby('quarter')['price'].median()
print("-"*49, "\nMedian Apartment prices by quarter - 2022:\n",median_apart_prices_by_quarter,"\n" + "-"*49, "\n")

apart_mean_median_price = median_apart_prices_by_quarter.mean()
print("-"*49, "\n Apartments' Mean of Median Prices:", apart_mean_median_price,
      "\n" + "-"*49, "\n")

# Step 3: Computing the index for each quarter
apart_index_by_quarter = (median_apart_prices_by_quarter / apart_mean_median_price)*100
print("-"*49, "\n Apartment Index Price for each quarter:\n", apart_index_by_quarter.to_string(float_format="%.4f"),
      "\n" + "-"*49, "\n")

# Compute the median price of houses for sale in 2022
median_apart_price_2022 = df_apart_2022['price'].median()
print("-"*49, "\n Median Price of Apartment for Sale in 2022:", round(median_apart_price_2022),"\n" + "-"*49, "\n")

sum_prices_apart = df_apart_2022['price'].sum()
print("-"*49, "\n Sum of prices of Apartments in Kigali City - 2022:", sum_prices_apart, 
      "\n" + "-"*49, "\n")

number_of_apartments = len(df_apart_2022) - 1  # Exclude header
print("-"*49, "\n Number of Apartments for sale in 2022:", number_of_apartments + 1,"\n" + "-"*49, "\n") # Start from index 1

-------------------------------------------------
Median Apartment prices by quarter - 2022:
 quarter
1    210000000.0
2    290000000.0
3     90000000.0
4     90000000.0
Name: price, dtype: float64
-------------------------------------------------

-------------------------------------------------
 Apartments' Mean of Median Prices: 170000000.0
-------------------------------------------------

-------------------------------------------------
 Apartment Index Price for each quarter:
 quarter
1   123.5294
2   170.5882
3    52.9412
4    52.9412
-------------------------------------------------

-------------------------------------------------
 Median Price of Apartment for Sale in 2022: 290000000
-------------------------------------------------

-------------------------------------------------
 Sum of prices of Apartments in Kigali City - 2022: 13835000000
-------------------------------------------------

-------------------------------------------------
 Number of Apartments for sale in 2022: 52
-------------------------------------------------

## II. Houses

In [73]:
## Preprocessing
df_house = pd.read_csv("house_for_sale.csv")

for idx, price in enumerate(df_house['price']):
    if price < 10000000:
        df_house.at[idx, 'price'] = 10000000
    elif price > 250000000:
        df_house.at[idx, 'price'] = 250000000
df_house['district'] = df_house['district'].str.lower().str.strip()
# Drop rows with missing values in the 'date' column
df_house = df_house.dropna(subset=['date'])
# Convert the 'date' column to a proper datetime format
df_house['date'] = pd.to_datetime(df_house['date'])
# Extracting the quarter from the 'date' column and creating a new 'quarter' column
df_house['quarter'] = df_house['date'].dt.quarter
desired_districts = ['gasabo', 'kicukiro', 'nyarugenge']
df_house_2022 = df_house[(df_house['district'].isin(desired_districts)) & (df_house['date'].dt.year == 2022)].copy()

# Computing the median price of houses for sale in 2022 by quarter
median_house_prices_by_quarter = df_house_2022.groupby('quarter')['price'].median()
print("-"*49, "\nMedian House prices by quarter - 2022:\n",median_house_prices_by_quarter,"\n" + "-"*49, "\n")

house_mean_median_price = median_house_prices_by_quarter.mean()
print("-"*49, "\n Houses' Mean of Median Prices:", house_mean_median_price,
      "\n" + "-"*49, "\n")

house_index_by_quarter = (median_house_prices_by_quarter / house_mean_median_price)*100
print("-"*49, "\n House Index Price for each quarter:\n", house_index_by_quarter.to_string(float_format="%.4f"),
      "\n" + "-"*49, "\n")
# Compute the median price of houses for sale in 2022
median_house_price_2022 = df_house_2022['price'].median()
print("-"*49, "\n Median Price of Houses for Sale in 2022:", round(median_house_price_2022),"\n" + "-"*49, "\n")

sum_prices_house = df_house_2022['price'].sum()
print("-"*49, "\n Sum of prices of Houses in Kigali City - 2022:", sum_prices_house, 
      "\n" + "-"*49, "\n")

number_of_houses = len(df_house_2022) - 1
print("-"*49, "\n Number of Houses for sale in 2022:", number_of_houses + 1,"\n" + "-"*49, "\n")

-------------------------------------------------
Median House prices by quarter - 2022:
 quarter
1    65000000.0
2    75000000.0
3    72000000.0
4    75000000.0
Name: price, dtype: float64
-------------------------------------------------

-------------------------------------------------
 Houses' Mean of Median Prices: 71750000.0
-------------------------------------------------

-------------------------------------------------
 House Index Price for each quarter:
 quarter
1    90.5923
2   104.5296
3   100.3484
4   104.5296
-------------------------------------------------

-------------------------------------------------
 Median Price of Houses for Sale in 2022: 72000000
-------------------------------------------------

-------------------------------------------------
 Sum of prices of Houses in Kigali City - 2022: 618946500008
-------------------------------------------------

-------------------------------------------------
 Number of Houses for sale in 2022: 6681
-------------------------------------------------

### Computing  Weight by Property Type

In [74]:
Total_property_prices = sum_prices_house + sum_prices_apart
print("-"*49, "\n Total Propetry price - 2022:", Total_property_prices, 
      "\n" + "-"*49, "\n")
weight_house = sum_prices_house / Total_property_prices
print("-"*49, "\n House Weight - 2022:", weight_house, 
      "\n" + "-"*49, "\n")
weight_apart = sum_prices_apart / Total_property_prices
print("-"*49, "\n Apartment Weight - 2022:", weight_apart, 
      "\n" + "-"*49, "\n")

-------------------------------------------------
 Total Propetry price - 2022: 632781500008
-------------------------------------------------

-------------------------------------------------
 House Weight - 2022: 0.9781362128952489
-------------------------------------------------

-------------------------------------------------
 Apartment Weight - 2022: 0.02186378710475115
-------------------------------------------------

### Computing Aggregate Index by Property Type

In [75]:
quarters = ['2022Q1', '2022Q2', '2022Q3', '2022Q4']
# Calculate property aggregate index values for each quarter and store them in a list
property_aggregate_indices = []

for quarter_str in quarters:
    quarter_int = int(quarter_str[-1])  # Convert '2022Q1' to 1
    if quarter_int in apart_index_by_quarter and quarter_int in house_index_by_quarter:
        property_aggregate_index = (apart_index_by_quarter[quarter_int] * weight_apart) + (house_index_by_quarter[quarter_int] * weight_house)
        property_aggregate_indices.append(property_aggregate_index)
        continue
    else:
        print(f"No data available for {quarter_str}")

# Combine quarters and aggregated index values
apart_data_aggr = list(zip(quarters, property_aggregate_indices))

# Print aggregated index values for each quarter
print("-" * 49)
print("Aggregated Index Price for each quarter:\n")
for quarter, value in apart_data_aggr:
    print(f"{quarter:<10} | {value:.4f}")
print("-" * 49 + "\n")

-------------------------------------------------
Aggregated Index Price for each quarter:

2022Q1     | 91.3125
2022Q2     | 105.9739
2022Q3     | 99.3119
2022Q4     | 103.4017
-------------------------------------------------

In [76]:
quarters = ['2022Q1', '2022Q2', '2022Q3', '2022Q4']
prop_data_apart = list(zip(quarters, apart_index_by_quarter.values)) #list of tuples
prop_data_house = list(zip(quarters, house_index_by_quarter.values))


# Create dataframes for each dataset
prop_df_house = pd.DataFrame(prop_data_house, columns=['Quarter', 'Houses'])
prop_df_apart = pd.DataFrame(prop_data_apart, columns=['Quarter', 'Apartments'])
prop_df_aggr = pd.DataFrame(apart_data_aggr, columns=['Quarter', 'Aggregated Index'])

# Merge dataframes on 'Quarter' column
prop_df_merged = pd.merge(prop_df_house, prop_df_apart, on='Quarter')
prop_df_merged = pd.merge(prop_df_merged, prop_df_aggr, on='Quarter')
prop_df_merged = prop_df_merged.round(2)


prop_df_merged.to_csv('property_indices_by_quarter.csv', index=False)

print(prop_df_merged)

  Quarter  Houses  Apartments  Aggregated Index
0  2022Q1   90.59      123.53             91.31
1  2022Q2  104.53      170.59            105.97
2  2022Q3  100.35       52.94             99.31
3  2022Q4  104.53       52.94            103.40

## II District

#### a) Apart

#### i) Gasabo

In [77]:
# Filter the data for Gasabo district in the year 2022
filtered_gasabo = df_apart_2022[(df_apart_2022['district'] == 'gasabo') & (df_apart_2022['date'].dt.year == 2022)].copy()

# Extracting the quarter from the 'date' column and creating a new 'quarter' column
filtered_gasabo['quarter'] = filtered_gasabo['date'].dt.quarter

# Computing the number of apart in Gasabo
num_apart_gasabo = len(filtered_gasabo)
print("-" * 49, "\n Number of Apartments in Gasabo district - 2022:", num_apart_gasabo,
      "\n" + "-" * 49, "\n")

# Step 1: Computing the median prices for each quarter
# gasabo_quarters_median_prices = filtered_gasabo.groupby('quarter')['price'].median().astype(int)
gasabo_quarters_median_prices = filtered_gasabo.groupby('quarter')['price'].median()
# If there are quarters without houses, set the median price to 0
quarters_without_houses = set([1, 2, 3, 4]) - set(gasabo_quarters_median_prices.index)
for quarter in quarters_without_houses:
    gasabo_quarters_median_prices.loc[quarter] = 0
gasabo_quarters_median_prices = gasabo_quarters_median_prices.sort_index()
print("-"*49, "\n 2022 Median prices for each quarter in Gasabo: \n", gasabo_quarters_median_prices, 
      "\n" + "-"*49, "\n")

gasabo_median_price = filtered_gasabo["price"].median()
print("-"*49, "\n Apartment Median Prices in Gasabo:", gasabo_median_price,
      "\n" + "-"*49, "\n")
# Step 2: Computing the mean of the median prices
gasabo_mean_median_price = gasabo_quarters_median_prices.mean()
print("-"*49, "\n Mean of Median Prices in Gasabo:", gasabo_mean_median_price,
      "\n" + "-"*49, "\n")

# Step 3: Computing the index for each quarter
gasabo_index_by_quarter = (gasabo_quarters_median_prices / gasabo_mean_median_price)*100
print("-"*49, "\n Index for each quarter in Gasabo:\n", gasabo_index_by_quarter.to_string(float_format="%.4f"),
      "\n" + "-"*49, "\n")

# Step 4: Compute the sum of prices for houses in Gasabo
sum_prices_apart_gasabo = filtered_gasabo['price'].sum()
print("-"*49, "\n Sum of prices in Gasabo district - 2022:", sum_prices_apart_gasabo, 
      "\n" + "-"*49, "\n")

-------------------------------------------------
 Number of Apartments in Gasabo district - 2022: 33
-------------------------------------------------

-------------------------------------------------
 2022 Median prices for each quarter in Gasabo:
 quarter
1    130000000.0
2    450000000.0
3     90000000.0
4     90000000.0
Name: price, dtype: float64
-------------------------------------------------

-------------------------------------------------
 Apartment Median Prices in Gasabo: 170000000.0
-------------------------------------------------

-------------------------------------------------
 Mean of Median Prices in Gasabo: 190000000.0
-------------------------------------------------

-------------------------------------------------
 Index for each quarter in Gasabo:
 quarter
1    68.4211
2   236.8421
3    47.3684
4    47.3684
-------------------------------------------------

-------------------------------------------------
 Sum of prices in Gasabo district - 2022: 8965000000
-------------------------------------------------

#### ii) Kicukiro

In [78]:
# Filter the data for Nyarugenge district in the year 2022
# filtered_kicukiro = df_house[df_house['district'].str.contains('Kicukiro') & df_house['date'].str.contains('2022')].copy()
filtered_kicukiro = df_apart_2022[(df_apart_2022['district'] == 'kicukiro') & (df_apart_2022['date'].dt.year == 2022)].copy()

# Extracting the quarter from the 'date' column and creating a new 'quarter' column
filtered_kicukiro['quarter'] = filtered_kicukiro['date'].dt.quarter

# Computing the number of houses in Kicukiro
num_apart_kicukiro = len(filtered_kicukiro)
print("-" * 49, "\n Number of Apartments in Kicukiro district - 2022:", num_apart_kicukiro,
      "\n" + "-" * 49, "\n")

# Step 1: Computing the median prices for each quarter
# kicukiro_quarters_median_prices = filtered_kicukiro.groupby('quarter')['price'].median().astype(int)
kicukiro_quarters_median_prices = filtered_kicukiro.groupby('quarter')['price'].median()
# If there are quarters without houses, set the median price to 0
quarters_without_houses = set([1, 2, 3, 4]) - set(kicukiro_quarters_median_prices.index)
for quarter in quarters_without_houses:
    kicukiro_quarters_median_prices.loc[quarter] = 0
kicukiro_quarters_median_prices = kicukiro_quarters_median_prices.sort_index()
print("-"*49, "\n 2022 Median prices for each quarter in Kicukiro: \n", kicukiro_quarters_median_prices, 
      "\n" + "-"*49, "\n")
kicukiro_median_price = filtered_kicukiro["price"].median()
print("-"*49, "\n Apartment Median Prices in Kicukiro:", kicukiro_median_price,
      "\n" + "-"*49, "\n")

# Step 2: Computing the mean of the median prices
kicukiro_mean_median_price = kicukiro_quarters_median_prices.mean()
print("-"*49, "\n Mean of Median Prices in Kicukiro:", kicukiro_mean_median_price,
      "\n" + "-"*49, "\n")

# Step 3: Computing the index for each quarter
kicukiro_index_by_quarter = (kicukiro_quarters_median_prices / kicukiro_mean_median_price)*100
print("-"*49, "\n Index for each quarter in Kicukiro:\n", kicukiro_index_by_quarter.to_string(float_format="%.4f"),
      "\n" + "-"*49, "\n")

# Step 4: Compute the sum of prices for houses in Kicukiro
sum_prices_apart_kicukiro = filtered_kicukiro['price'].sum()
print("-"*49, "\n Sum of prices in Kicukiro district - 2022:", sum_prices_apart_kicukiro, 
      "\n" + "-"*49)

-------------------------------------------------
 Number of Apartments in Kicukiro district - 2022: 11
-------------------------------------------------

-------------------------------------------------
 2022 Median prices for each quarter in Kicukiro:
 quarter
1    210000000.0
2    210000000.0
3            0.0
4            0.0
Name: price, dtype: float64
-------------------------------------------------

-------------------------------------------------
 Apartment Median Prices in Kicukiro: 210000000.0
-------------------------------------------------

-------------------------------------------------
 Mean of Median Prices in Kicukiro: 105000000.0
-------------------------------------------------

-------------------------------------------------
 Index for each quarter in Kicukiro:
 quarter
1   200.0000
2   200.0000
3     0.0000
4     0.0000
-------------------------------------------------

-------------------------------------------------
 Sum of prices in Kicukiro district - 2022: 2550000000
-------------------------------------------------

In [79]:
filtered_kicukiro

,date,build_year,floors,sitting_rooms,dining_rooms,bedrooms,wardrobes,bathrooms,car_parking,ancillary,landsize,price,district,sector,quarter
23,2022-06-20 08:42:51,2019,0,0,0,0,0,0,0,0,708,150000000,kicukiro,Nyarugunga,2
25,2022-06-11 13:36:47,2022,0,0,0,10,0,10,0,0,300,350000000,kicukiro,Kicukiro,2
27,2022-05-26 14:40:41,2022,0,1,0,10,0,10,1,0,300,350000000,kicukiro,Kicukiro,2
28,2022-05-26 14:15:01,2022,0,0,0,0,0,0,0,0,300,210000000,kicukiro,Niboye,2
30,2022-05-15 08:01:28,2022,0,0,0,10,0,10,0,0,300,350000000,kicukiro,Kicukiro,2
48,2022-04-21 23:27:32,2022,1,0,0,0,0,0,1,0,300,210000000,kicukiro,Niboye,2
56,2022-04-05 16:35:40,2022,0,1,1,1,1,1,0,0,300,90000000,kicukiro,Kanombe,2
58,2022-04-01 14:50:51,2022,1,0,0,0,0,0,1,0,300,210000000,kicukiro,Niboye,2
62,2022-02-19 13:00:43,2022,1,1,1,0,0,0,0,0,300,210000000,kicukiro,Niboye,1
63,2022-02-18 07:43:36,2022,1,0,0,0,0,0,0,0,300,210000000,kicukiro,Niboye,1
65,2022-02-15 12:41:53,2022,1,0,0,0,0,0,1,0,300,210000000,kicukiro,Niboye,1

In [80]:
# function to compute moving average
def calculate_moving_average(data, window_size):
    moving_avg = data.rolling(window=window_size, min_periods=1).mean() #even if there is only one data point available in the window, the moving average is still calculated.
    return moving_avg

window_size = 2 # Nbr of missing quarters
moving_avg_indices = calculate_moving_average(kicukiro_index_by_quarter, window_size)

# missing indices
for quarter in quarters_without_houses:
    if quarter == 3 or quarter == 4:
        kicukiro_index_by_quarter.loc[quarter] = moving_avg_indices.loc[quarter]

print("-"*49, "\n Estimated Index for each quarter in Kicukiro (including estimated values):\n", 
      kicukiro_index_by_quarter.to_string(float_format="%.4f"),
      "\n" + "-"*49, "\n")

-------------------------------------------------
 Estimated Index for each quarter in Kicukiro (including estimated values):
 quarter
1   200.0000
2   200.0000
3   100.0000
4     0.0000
-------------------------------------------------

In [81]:
def calculate_moving_average(data, window_size):
    moving_avg = data.rolling(window=window_size, min_periods=1).mean()
    return moving_avg

window_size = 2

moving_avg_indices = calculate_moving_average(kicukiro_index_by_quarter, window_size)

estimated_index_q3 = 2 * moving_avg_indices.loc[2] - moving_avg_indices.loc[1]
kicukiro_index_by_quarter.loc[3] = estimated_index_q3

estimated_index_q4 = 2 * moving_avg_indices.loc[3] - moving_avg_indices.loc[2]
kicukiro_index_by_quarter.loc[4] = estimated_index_q4

# Print the estimated indices
print("-"*49, "\n Estimated Index for each quarter in Kicukiro (including estimated values):\n", 
      kicukiro_index_by_quarter.to_string(float_format="%.4f"),
      "\n" + "-"*49, "\n")

-------------------------------------------------
 Estimated Index for each quarter in Kicukiro (including estimated values):
 quarter
1   200.0000
2   200.0000
3   200.0000
4   100.0000
-------------------------------------------------

#### iii) Nyarugenge

In [82]:
filtered_nyarugenge = df_apart_2022[(df_apart_2022['district'] == 'nyarugenge') & (df_apart_2022['date'].dt.year == 2022)].copy()

# Extracting the quarter from the 'date' column and creating a new 'quarter' column
filtered_nyarugenge['quarter'] = filtered_nyarugenge['date'].dt.quarter

# Computing the number of houses in Nyarugenge
num_apart_nyarugenge = len(filtered_nyarugenge)
print("-" * 49, "\n Number of Apartments in Nyarugenge district - 2022:", num_apart_nyarugenge,
      "\n" + "-" * 49, "\n")


# Step 1: Computing the median prices for each quarter
nyarugenge_quarters_median_prices = filtered_nyarugenge.groupby('quarter')['price'].median()
# If there are quarters without houses, set the median price to 0
quarters_without_houses = set([1, 2, 3, 4]) - set(nyarugenge_quarters_median_prices.index)
for quarter in quarters_without_houses:
    nyarugenge_quarters_median_prices.loc[quarter] = 0
nyarugenge_quarters_median_prices = nyarugenge_quarters_median_prices.sort_index()
print("-"*49, "\n 2022 Median prices for each quarter in Nyarugenge: \n", nyarugenge_quarters_median_prices, 
      "\n" + "-"*49, "\n")
nyarugenge_median_price = filtered_nyarugenge["price"].median()
print("-"*49, "\n Apartment Median Prices in Nyarugenge:", nyarugenge_median_price,
      "\n" + "-"*49, "\n")

# Step 2: Computing the mean of the median prices
nyarugenge_mean_median_price = nyarugenge_quarters_median_prices.mean()
print("-"*49, "\n Mean of Median Prices in Nyarugenge:", nyarugenge_mean_median_price,
      "\n" + "-"*49, "\n")

# Step 3: Computing the index for each quarter
nyarugenge_index_by_quarter = (nyarugenge_quarters_median_prices / nyarugenge_mean_median_price)*100
print("-"*49, "\n Index for each quarter in Nyarugenge:\n", nyarugenge_index_by_quarter.to_string(float_format="%.4f"),
      "\n" + "-"*49, "\n")

# Step 4: Compute the sum of prices for houses in Nyarugenge
sum_prices_apart_nyarugenge= filtered_nyarugenge['price'].sum()
print("-"*49, "\n Sum of prices in Nyarugenge district - 2022:", sum_prices_apart_nyarugenge, 
      "\n" + "-"*49, "\n")

-------------------------------------------------
 Number of Apartments in Nyarugenge district - 2022: 8
-------------------------------------------------

-------------------------------------------------
 2022 Median prices for each quarter in Nyarugenge:
 quarter
1            0.0
2    290000000.0
3            0.0
4            0.0
Name: price, dtype: float64
-------------------------------------------------

-------------------------------------------------
 Apartment Median Prices in Nyarugenge: 290000000.0
-------------------------------------------------

-------------------------------------------------
 Mean of Median Prices in Nyarugenge: 72500000.0
-------------------------------------------------

-------------------------------------------------
 Index for each quarter in Nyarugenge:
 quarter
1     0.0000
2   400.0000
3     0.0000
4     0.0000
-------------------------------------------------

-------------------------------------------------
 Sum of prices in Nyarugenge district - 2022: 2320000000
-------------------------------------------------

#### Apart weight by District

In [83]:
## Total price for base period (2022)
Total_apart_prices = sum_prices_apart_gasabo + sum_prices_apart_kicukiro + sum_prices_apart_nyarugenge
print("-"*49, "\n Total price (Apartment) - 2022:", Total_apart_prices, 
      "\n" + "-"*49, "\n")
## District weight
apart_weight_gasabo = sum_prices_apart_gasabo / Total_apart_prices
print("-"*49, "\n Gasabo's Apartment Weight - 2022:", apart_weight_gasabo, 
      "\n" + "-"*49, "\n")
apart_weight_kicukiro = sum_prices_apart_kicukiro / Total_apart_prices
print("-"*49, "\n Kicukiro's Apartment Weight - 2022:", apart_weight_kicukiro, 
      "\n" + "-"*49, "\n")
apart_weight_nyarugenge = sum_prices_apart_nyarugenge / Total_apart_prices
print("-"*49, "\n Nyarugenge's Apartment Weight - 2022:", apart_weight_nyarugenge, 
      "\n" + "-"*49, "\n")

-------------------------------------------------
 Total price (Apartment) - 2022: 13835000000
-------------------------------------------------

-------------------------------------------------
 Gasabo's Apartment Weight - 2022: 0.6479942175641489
-------------------------------------------------

-------------------------------------------------
 Kicukiro's Apartment Weight - 2022: 0.18431514275388508
-------------------------------------------------

-------------------------------------------------
 Nyarugenge's Apartment Weight - 2022: 0.16769063968196604
-------------------------------------------------

In [84]:
# # Step 5: Compute the aggregate indices

# # Quarter 1
# apart_aggregate_index_q1 = (gasabo_index_by_quarter[1] * apart_weight_gasabo) 
# + (nyarugenge_index_by_quarter[1] * apart_weight_nyarugenge)
# + (kicukiro_index_by_quarter[1] * apart_weight_kicukiro)
# # Step 14: Print the aggregate index for each quarter
# print("-"*49, "\n Apartment Aggregate Index for quarter 1 =", apart_aggregate_index_q1,"\n" + "-"*49,"\n")

# # Quarter 2
# apart_aggregate_index_q2 = (gasabo_index_by_quarter[2] * apart_weight_gasabo)
# + (nyarugenge_index_by_quarter[2] * apart_weight_nyarugenge)
# + (kicukiro_index_by_quarter[2] * apart_weight_kicukiro)
# # Step 14: Print the aggregate index for each quarter
# print("-"*49, "\n Apartment Aggregate Index for quarter 2 =", apart_aggregate_index_q2,"\n" + "-"*49,"\n")

# # Quarter 3
# apart_aggregate_index_q3 = (gasabo_index_by_quarter[3] * apart_weight_gasabo) + (nyarugenge_index_by_quarter[3] * apart_weight_nyarugenge) + (kicukiro_index_by_quarter[3] * apart_weight_kicukiro)
# # Step 14: Print the aggregate index for each quarter
# print("-"*49, "\n Apartment Aggregate Index for quarter 3 =", apart_aggregate_index_q1,"\n" + "-"*49,"\n")

# # Quarter 4
# apart_aggregate_index_q4 = (gasabo_index_by_quarter[4] * apart_weight_gasabo )
# + (nyarugenge_index_by_quarter[4] * apart_weight_nyarugenge)
# + (kicukiro_index_by_quarter[4] * apart_weight_kicukiro)
# # Step 14: Print the aggregate index for each quarter
# print("-"*49, "\n Apartment Aggregate Index for quarter 4 =", apart_aggregate_index_q1,"\n" + "-"*49)

In [85]:
# Calculate apartment aggregate index values for each quarter and store them in a list
apartment_aggregate_indices_by_district = []

for quarter_str in quarters:
    quarter_int = int(quarter_str[-1])  # Convert '2022Q1' to 1
    if quarter_int in gasabo_index_by_quarter and quarter_int in nyarugenge_index_by_quarter and quarter_int in kicukiro_index_by_quarter:
        apart_aggregate_index_dist = (gasabo_index_by_quarter[quarter_int] * apart_weight_gasabo) + (nyarugenge_index_by_quarter[quarter_int] * apart_weight_nyarugenge) + (kicukiro_index_by_quarter[quarter_int] * apart_weight_kicukiro)
        apartment_aggregate_indices_by_district.append(apart_aggregate_index_dist)
        continue
    else:
        print(f"No data available for {quarter_str}")

# Combine quarters and apartment aggregated index values
apartment_aggregate_data_by_district = list(zip(quarters, apartment_aggregate_indices_by_district))

# Print apartment aggregated index values for each quarter
print("-" * 49)
print("Apartment Aggregate Index for each quarter:\n")
for quarter, value in apartment_aggregate_data_by_district:
    print(f"{quarter:<10} | {value:.4f}")
print("-" * 49 + "\n")

-------------------------------------------------
Apartment Aggregate Index for each quarter:

2022Q1     | 81.1995
2022Q2     | 257.4116
2022Q3     | 67.5575
2022Q4     | 49.1260
-------------------------------------------------

In [86]:
quarters = ['2022Q1', '2022Q2', '2022Q3', '2022Q4']
data_apart_gasabo = list(zip(quarters, gasabo_index_by_quarter.values)) #list of tuples
data_apart_nyarugenge = list(zip(quarters, nyarugenge_index_by_quarter.values))
data_apart_kicukiro = list(zip(quarters, kicukiro_index_by_quarter.values))


# Create dataframes for each dataset
df_apart_gasabo = pd.DataFrame(data_apart_gasabo, columns=['Quarter', 'Gasabo'])
df_apart_kicukiro = pd.DataFrame(data_apart_kicukiro, columns=['Quarter', 'Kicukiro'])
df_apart_nyarugenge = pd.DataFrame(data_apart_nyarugenge, columns=['Quarter', 'Nyarugenge'])
df_apart_aggr = pd.DataFrame(apartment_aggregate_data_by_district, columns=['Quarter', 'Aggregate Index'])

# Merge dataframes on 'Quarter' column
apart_df_merged = pd.merge(df_apart_gasabo, df_apart_kicukiro, on='Quarter')
apart_df_merged = pd.merge(apart_df_merged, df_apart_nyarugenge, on='Quarter')
apart_df_merged = pd.merge(apart_df_merged, df_apart_aggr, on='Quarter')
apart_df_merged = apart_df_merged.round(2)


apart_df_merged.to_csv('apartment_indices_by_quarter(district).csv', index=False)

print(apart_df_merged)

  Quarter  Gasabo  Kicukiro  Nyarugenge  Aggregate Index
0  2022Q1   68.42     200.0         0.0            81.20
1  2022Q2  236.84     200.0       400.0           257.41
2  2022Q3   47.37     200.0         0.0            67.56
3  2022Q4   47.37     100.0         0.0            49.13

#### b) Houses

#### i) Gasabo

In [87]:
# Filter the data for Gasabo district in the year 2022
filtered_gasabo_house = df_house[(df_house['district'] == 'gasabo') & (df_house['date'].dt.year == 2022)].copy()

# Extracting the quarter from the 'date' column and creating a new 'quarter' column
filtered_gasabo_house['quarter'] = filtered_gasabo_house['date'].dt.quarter

# Computing the number of houses in Gasabo
num_houses_gasabo = len(filtered_gasabo_house)
print("-" * 49, "\n Number of houses in Gasabo district - 2022:", num_houses_gasabo,
      "\n" + "-" * 49, "\n")

# Step 1: Computing the median prices for each quarter
# gasabo_quarters_median_prices = filtered_gasabo.groupby('quarter')['price'].median().astype(int)
gasabo_quarters_median_prices_house  = filtered_gasabo_house.groupby('quarter')['price'].median()
print("-"*49, "\n 2022 Median prices for each quarter in Gasabo: \n", gasabo_quarters_median_prices_house, 
      "\n" + "-"*49, "\n")
house_gasabo_median_price = filtered_gasabo_house["price"].median()
print("-"*49, "\n House Median Prices in Gasabo:", house_gasabo_median_price,
      "\n" + "-"*49, "\n")

# Step 2: Computing the mean of the median prices
gasabo_mean_median_price_house  = gasabo_quarters_median_prices_house .mean()
print("-"*49, "\n Mean of Median House Prices in Gasabo:", gasabo_mean_median_price_house ,
      "\n" + "-"*49, "\n")

# Step 3: Computing the index for each quarter
gasabo_index_by_quarter_house  = (gasabo_quarters_median_prices_house / gasabo_mean_median_price_house )*100
print("-"*49, "\n Index for each house's quarter in Gasabo:\n", gasabo_index_by_quarter_house.to_string(float_format="%.4f"),
      "\n" + "-"*49, "\n")

# Step 4: Compute the sum of prices for houses in Gasabo
sum_prices_gasabo_house  = filtered_gasabo_house['price'].sum()
print("-"*49, "\n Sum of prices in Gasabo district - 2022:", sum_prices_gasabo_house , 
      "\n" + "-"*49, "\n")

-------------------------------------------------
 Number of houses in Gasabo district - 2022: 3438
-------------------------------------------------

-------------------------------------------------
 2022 Median prices for each quarter in Gasabo:
 quarter
1     85000000.0
2     95000000.0
3     95000000.0
4    100000000.0
Name: price, dtype: float64
-------------------------------------------------

-------------------------------------------------
 House Median Prices in Gasabo: 95000000.0
-------------------------------------------------

-------------------------------------------------
 Mean of Median House Prices in Gasabo: 93750000.0
-------------------------------------------------

-------------------------------------------------
 Index for each house's quarter in Gasabo:
 quarter
1    90.6667
2   101.3333
3   101.3333
4   106.6667
-------------------------------------------------

-------------------------------------------------
 Sum of prices in Gasabo district - 2022: 388776000000
-------------------------------------------------

#### ii) Kicukiro

In [88]:
# Filter the data for Nyarugenge district in the year 2022
# filtered_kicukiro = df_house[df_house['district'].str.contains('Kicukiro') & df_house['date'].str.contains('2022')].copy()
filtered_kicukiro_house = df_house[(df_house['district'] == 'kicukiro') & (df_house['date'].dt.year == 2022)].copy()

# Extracting the quarter from the 'date' column and creating a new 'quarter' column
filtered_kicukiro_house['quarter'] = filtered_kicukiro_house['date'].dt.quarter

# Computing the number of houses in Nyarugenge
num_houses_kicukiro = len(filtered_kicukiro_house)
print("-" * 49, "\n Number of houses in Kicukiro district - 2022:", num_houses_kicukiro,
      "\n" + "-" * 49, "\n")

# Step 1: Computing the median prices for each quarter
# kicukiro_quarters_median_prices = filtered_kicukiro.groupby('quarter')['price'].median().astype(int)
kicukiro_quarters_median_prices_house = filtered_kicukiro_house.groupby('quarter')['price'].median()
print("-"*49, "\n 2022 Median prices for each quarter in Kicukiro: \n", kicukiro_quarters_median_prices_house, 
      "\n" + "-"*49, "\n")
kicukiro_median_price_house = filtered_kicukiro_house["price"].median()
print("-"*49, "\n House Median Prices in Kicukiro:", kicukiro_median_price_house,
      "\n" + "-"*49, "\n")

# Step 2: Computing the mean of the median prices
kicukiro_mean_median_price_house = kicukiro_quarters_median_prices_house.mean()
print("-"*49, "\n Mean of Median Prices in Kicukiro:", kicukiro_mean_median_price_house,
      "\n" + "-"*49, "\n")

# Step 3: Computing the index for each quarter
kicukiro_index_by_quarter_house = (kicukiro_quarters_median_prices_house / kicukiro_mean_median_price_house)*100
print("-"*49, "\n Index for each quarter in Kicukiro:\n", kicukiro_index_by_quarter_house.to_string(float_format="%.4f"),
      "\n" + "-"*49, "\n")

# Step 4: Compute the sum of prices for houses in Kicukiro
sum_prices_kicukiro_house = filtered_kicukiro_house['price'].sum()
print("-"*49, "\n Sum of prices in Kicukiro district - 2022:", sum_prices_kicukiro_house, 
      "\n" + "-"*49)

-------------------------------------------------
 Number of houses in Kicukiro district - 2022: 3206
-------------------------------------------------

-------------------------------------------------
 2022 Median prices for each quarter in Kicukiro:
 quarter
1    60000000.0
2    65000000.0
3    65000000.0
4    68000000.0
Name: price, dtype: float64
-------------------------------------------------

-------------------------------------------------
 House Median Prices in Kicukiro: 65000000.0
-------------------------------------------------

-------------------------------------------------
 Mean of Median Prices in Kicukiro: 64500000.0
-------------------------------------------------

-------------------------------------------------
 Index for each quarter in Kicukiro:
 quarter
1    93.0233
2   100.7752
3   100.7752
4   105.4264
-------------------------------------------------

-------------------------------------------------
 Sum of prices in Kicukiro district - 2022: 226100500008
-------------------------------------------------

#### iii) Nyarugenge

In [89]:
# Filter the data for Nyarugenge district in the year 2022
df_house = df_house.dropna(subset=['date'])
# filtered_nyarugenge = df_house[df_house['district'].str.contains('Nyarugenge') & df_house['date'].str.contains('2022')].copy()
filtered_nyarugenge_house = df_house[(df_house['district'] == 'nyarugenge') & (df_house['date'].dt.year == 2022)].copy()

# Extracting the quarter from the 'date' column and creating a new 'quarter' column
filtered_nyarugenge_house['quarter'] = filtered_nyarugenge_house['date'].dt.quarter

# Computing the number of houses in Nyarugenge
num_houses_nyarugenge = len(filtered_nyarugenge_house)
print("-" * 49, "\n Number of houses in Nyarugenge district - 2022:", num_houses_nyarugenge,
      "\n" + "-" * 49, "\n")

house_nyarugenge_median_price = filtered_nyarugenge_house["price"].median()
print("-"*49, "\n House Median Prices in Gasabo:", house_nyarugenge_median_price,
      "\n" + "-"*49, "\n")

# Step 1: Computing the median prices for each quarter
nyarugenge_quarters_median_prices_house = filtered_nyarugenge_house.groupby('quarter')['price'].median()
# If there are quarters without houses, set the median price to 0
quarters_without_houses = set([1, 2, 3, 4]) - set(nyarugenge_quarters_median_prices_house.index)
for quarter in quarters_without_houses:
    nyarugenge_quarters_median_prices_house.loc[quarter] = 0
nyarugenge_quarters_median_prices_house = nyarugenge_quarters_median_prices_house.sort_index()
print("-"*49, "\n 2022 Median prices for each quarter in Nyarugenge: \n", nyarugenge_quarters_median_prices_house, 
      "\n" + "-"*49, "\n")


# Step 2: Computing the mean of the median prices
nyarugenge_mean_median_price_house = nyarugenge_quarters_median_prices_house.mean()
print("-"*49, "\n Mean of Median Prices in Nyarugenge:", nyarugenge_mean_median_price_house,
      "\n" + "-"*49, "\n")

# Step 3: Computing the index for each quarter
nyarugenge_index_by_quarter_house = (nyarugenge_quarters_median_prices_house / nyarugenge_mean_median_price_house)*100
print("-"*49, "\n Index for each quarter in Nyarugenge:\n", nyarugenge_index_by_quarter_house.to_string(float_format="%.4f"),
      "\n" + "-"*49, "\n")

# Step 4: Compute the sum of prices for houses in Nyarugenge
sum_prices_nyarugenge_house = filtered_nyarugenge_house['price'].sum()
print("-"*49, "\n Sum of prices in Nyarugenge district - 2022:", sum_prices_nyarugenge_house, 
      "\n" + "-"*49, "\n")

-------------------------------------------------
 Number of houses in Nyarugenge district - 2022: 37
-------------------------------------------------

-------------------------------------------------
 House Median Prices in Gasabo: 55000000.0
-------------------------------------------------

-------------------------------------------------
 2022 Median prices for each quarter in Nyarugenge:
 quarter
1     55000000.0
2    130000000.0
3     50000000.0
4    167500000.0
Name: price, dtype: float64
-------------------------------------------------

-------------------------------------------------
 Mean of Median Prices in Nyarugenge: 100625000.0
-------------------------------------------------

-------------------------------------------------
 Index for each quarter in Nyarugenge:
 quarter
1    54.6584
2   129.1925
3    49.6894
4   166.4596
-------------------------------------------------

-------------------------------------------------
 Sum of prices in Nyarugenge district - 2022: 4070000000
-------------------------------------------------

### House Weight by District

In [90]:
## Total price for base period (2022)
Total_house_prices = sum_prices_gasabo_house + sum_prices_kicukiro_house + sum_prices_nyarugenge_house
print("-"*49, "\n Total price (Houses) - 2022:", Total_house_prices, 
      "\n" + "-"*49, "\n")
## District weight
house_weight_gasabo = sum_prices_gasabo_house / Total_house_prices
print("-"*49, "\n Gasabo's House Weight - 2022:", house_weight_gasabo, 
      "\n" + "-"*49, "\n")
house_weight_kicukiro = sum_prices_kicukiro_house / Total_house_prices
print("-"*49, "\n Kicukiro's House Weight - 2022:", house_weight_kicukiro, 
      "\n" + "-"*49, "\n")
house_weight_nyarugenge = sum_prices_nyarugenge_house / Total_house_prices
print("-"*49, "\n Nyarugenge's House Weight - 2022:", house_weight_nyarugenge, 
      "\n" + "-"*49, "\n")

-------------------------------------------------
 Total price (Houses) - 2022: 618946500008
-------------------------------------------------

-------------------------------------------------
 Gasabo's House Weight - 2022: 0.6281253710861521
-------------------------------------------------

-------------------------------------------------
 Kicukiro's House Weight - 2022: 0.36529893941572916
-------------------------------------------------

-------------------------------------------------
 Nyarugenge's House Weight - 2022: 0.006575689498118811
-------------------------------------------------

### Aggregate indices

In [91]:
# Calculate apartment aggregate index values for each quarter and store them in a list
house_aggregate_indices_by_district = []

for quarter_str in quarters:
    quarter_int = int(quarter_str[-1])  # Convert '2022Q1' to 1
    if quarter_int in gasabo_index_by_quarter_house and quarter_int in nyarugenge_index_by_quarter_house and quarter_int in kicukiro_index_by_quarter_house:
        house_aggregate_index_dist = (gasabo_index_by_quarter_house[quarter_int] * house_weight_gasabo) + (nyarugenge_index_by_quarter_house[quarter_int] * house_weight_nyarugenge) + (kicukiro_index_by_quarter_house[quarter_int] * house_weight_kicukiro)
        house_aggregate_indices_by_district.append(house_aggregate_index_dist)
        continue
    else:
        print(f"No data available for {quarter_str}")

# Combine quarters and apartment aggregated index values
house_aggregate_data_by_district = list(zip(quarters, house_aggregate_indices_by_district))

# Print apartment aggregated index values for each quarter
print("-" * 49)
print("House Aggregate Index for each quarter:\n")
for quarter, value in house_aggregate_data_by_district:
    print(f"{quarter:<10} | {value:.4f}")
print("-" * 49 + "\n")

-------------------------------------------------
House Aggregate Index for each quarter:

2022Q1     | 91.2907
2022Q2     | 101.3126
2022Q3     | 100.7899
2022Q4     | 106.6068
-------------------------------------------------

In [92]:
data_house_gasabo = list(zip(quarters, gasabo_index_by_quarter_house.values)) #list of tuples
data_house_nyarugenge = list(zip(quarters, nyarugenge_index_by_quarter_house.values))
data_house_kicukiro = list(zip(quarters, kicukiro_index_by_quarter_house.values))


# Create dataframes for each dataset
df_house_gasabo = pd.DataFrame(data_house_gasabo, columns=['Quarter', 'Gasabo'])
df_house_kicukiro = pd.DataFrame(data_house_kicukiro, columns=['Quarter', 'Kicukiro'])
df_house_nyarugenge = pd.DataFrame(data_house_nyarugenge, columns=['Quarter', 'Nyarugenge'])
df_house_aggr = pd.DataFrame(house_aggregate_data_by_district, columns=['Quarter', 'Aggregate Index'])

# Merge dataframes on 'Quarter' column
house_df_merged = pd.merge(df_house_gasabo, df_house_kicukiro, on='Quarter')
house_df_merged = pd.merge(house_df_merged, df_house_nyarugenge, on='Quarter')
house_df_merged = pd.merge(house_df_merged, df_house_aggr, on='Quarter')
house_df_merged = house_df_merged.round(2)


house_df_merged.to_csv('house_indices_by_quarter(district).csv', index=False)

print(house_df_merged)

  Quarter  Gasabo  Kicukiro  Nyarugenge  Aggregate Index
0  2022Q1   90.67     93.02       54.66            91.29
1  2022Q2  101.33    100.78      129.19           101.31
2  2022Q3  101.33    100.78       49.69           100.79
3  2022Q4  106.67    105.43      166.46           106.61

In [93]:
locations = ['Gasabo', 'Kicukiro', 'Nyarugenge']
num_houses = [num_houses_gasabo, num_houses_kicukiro, num_houses_nyarugenge]
num_apartments = [num_apart_gasabo, num_apart_kicukiro, num_apart_nyarugenge]

data = {
    'Location': locations,
    'Houses': num_houses,
    'Apartments': num_apartments
}

df = pd.DataFrame(data)
# Add a row for summation
df.loc['Total'] = df[['Houses', 'Apartments']].sum()

csv_filename = 'property_distribution.csv'  # Alternative name
df.to_csv(csv_filename, index=False)

print(f"Dataframe saved as '{csv_filename}'")

Dataframe saved as 'property_distribution.csv'

In [94]:
## Total price for base period (2022)
Total_apart_prices = sum_prices_apart_gasabo + sum_prices_apart_kicukiro + sum_prices_apart_nyarugenge
print("-"*49, "\n Total price (Apartment) - 2022:", Total_apart_prices, 
      "\n" + "-"*49, "\n")
## District weight
apart_weight_gasabo = sum_prices_apart_gasabo / Total_apart_prices
print("-"*49, "\n Gasabo's Apartment Weight - 2022:", apart_weight_gasabo, 
      "\n" + "-"*49, "\n")
apart_weight_kicukiro = sum_prices_apart_kicukiro / Total_apart_prices
print("-"*49, "\n Kicukiro's Apartment Weight - 2022:", apart_weight_kicukiro, 
      "\n" + "-"*49, "\n")
apart_weight_nyarugenge = sum_prices_apart_nyarugenge / Total_apart_prices
print("-"*49, "\n Nyarugenge's Apartment Weight - 2022:", apart_weight_nyarugenge, 
      "\n" + "-"*49, "\n")

## Total price for base period (2022)
Total_house_prices = sum_prices_gasabo_house + sum_prices_kicukiro_house + sum_prices_nyarugenge_house
print("-"*49, "\n Total price (Houses) - 2022:", Total_house_prices, 
      "\n" + "-"*49, "\n")
## District weight
house_weight_gasabo = sum_prices_gasabo_house / Total_house_prices
print("-"*49, "\n Gasabo's House Weight - 2022:", house_weight_gasabo, 
      "\n" + "-"*49, "\n")
house_weight_kicukiro = sum_prices_kicukiro_house / Total_house_prices
print("-"*49, "\n Kicukiro's House Weight - 2022:", house_weight_kicukiro, 
      "\n" + "-"*49, "\n")
house_weight_nyarugenge = sum_prices_nyarugenge_house / Total_house_prices
print("-"*49, "\n Nyarugenge's House Weight - 2022:", house_weight_nyarugenge, 
      "\n" + "-"*49, "\n")

-------------------------------------------------
 Total price (Apartment) - 2022: 13835000000
-------------------------------------------------

-------------------------------------------------
 Gasabo's Apartment Weight - 2022: 0.6479942175641489
-------------------------------------------------

-------------------------------------------------
 Kicukiro's Apartment Weight - 2022: 0.18431514275388508
-------------------------------------------------

-------------------------------------------------
 Nyarugenge's Apartment Weight - 2022: 0.16769063968196604
-------------------------------------------------

-------------------------------------------------
 Total price (Houses) - 2022: 618946500008
-------------------------------------------------

-------------------------------------------------
 Gasabo's House Weight - 2022: 0.6281253710861521
-------------------------------------------------

-------------------------------------------------
 Kicukiro's House Weight - 2022: 0.36529893941572916
-------------------------------------------------

-------------------------------------------------
 Nyarugenge's House Weight - 2022: 0.006575689498118811
-------------------------------------------------

In [95]:
Total_apart_prices = sum_prices_apart_gasabo + sum_prices_apart_kicukiro + sum_prices_apart_nyarugenge

# Calculate district apartment weights
apart_weight_gasabo = sum_prices_apart_gasabo / Total_apart_prices
apart_weight_kicukiro = sum_prices_apart_kicukiro / Total_apart_prices
apart_weight_nyarugenge = sum_prices_apart_nyarugenge / Total_apart_prices

# Calculate total house prices
Total_house_prices = sum_prices_gasabo_house + sum_prices_kicukiro_house + sum_prices_nyarugenge_house

# Calculate district house weights
house_weight_gasabo = sum_prices_gasabo_house / Total_house_prices
house_weight_kicukiro = sum_prices_kicukiro_house / Total_house_prices
house_weight_nyarugenge = sum_prices_nyarugenge_house / Total_house_prices

# Create a dictionary with the calculated weights
data = {
    "District": ["Gasabo", "Kicukiro", "Nyarugenge"],
    "Apartment_Weight": [apart_weight_gasabo, apart_weight_kicukiro, apart_weight_nyarugenge],
    "House_Weight": [house_weight_gasabo, house_weight_kicukiro, house_weight_nyarugenge]
}

# Create a dataframe
weights_df = pd.DataFrame(data)

# Save the dataframe to a CSV file
weights_df.to_csv("district_weights.csv", index=False)

print("District weights saved to district_weights.csv")

District weights saved to district_weights.csv